development:
      host: 127.0.0.1
      adapter: mysql
      database: fedena
      port: 3306
      username: fedena
      password: fedena

test: &test
      host: localhost
      adapter: mysql
      database: fedena_test
      port: 3306
      username: admin
      password:

production:
      host: localhost
      adapter: mysql
      database: fedena
      port: 3306
      username: admin
      password: 
cucumber:
  <<: *test
